from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, IntegerField, DateField

#>>> python
#>>> import os
#>>> os.urandom(12).hex()
#'<secret key generated by os.urandom()>'
# this is the secret key for the form
class RegisterationForm(FlaskForm):
    username = StringField('Username')
    email = StringField('Email')
    password1 = PasswordField('Password')
    password2 = PasswordField('Confirm Password')
    submit = SubmitField('Sign Up') 